### ISSUE TITLE
Using `include KSUID::ActiveRecord` always initializes the attribute with a new KSUID

### ISSUE THREAD

**Issue by stormmaster42** [michaelherold/ksuid-ruby#38]
We have been using `include KSUID::ActiveRecord[:project_id]` to declare KSUID attributes in models.

That's no problem for primary keys ("id"). For foreign keys this leads to the attribute initialized with a default KSUID, because of the default. OK and necessary for primary keys; not necessary and misleading for foreign keys.

I will no suggest to declare ksuid foreign keys with 
```
attribute :project_id, :ksuid
```
instead.

Theoretically it would be nice if this could be derived from introspecting the relationship.

Or am I missing something?

One solution might be to have a separate concern for primary and foreign keys or to make setting the default optional somehow.

**Comment by michaelherold** [comment]
This is a good catch, thanks! I will look into what we can do. You're also welcome to submit a patch.

**Comment by michaelherold** [comment]
@stormmaster42 how does the solution in #39 look to you?

You also have the option to use `attribute` directly, which I am going to start documenting. I think the module builder approach buys us very little at this point so I'm considering deprecating it for v2.0.

**Comment by stormmaster42** [comment]
So I have been switching to the attribute declaration in my project for all but primary keys, so I would not need this fix.
If you are going to deprecate the module builder (which I think is a good idea), I do not see a point in adding the option now, as there is a workaround using the attribute declaration.
+1 for adding it to the documentation.

**Comment by michaelherold** [comment]
After some thought, I decided to go ahead and merge #39. I want to migrate people to using the `attribute` directly instead of the builder, but I made that decision after I prepared the upgrade path from 0.x to 1.0. Retrofitting that deprecation and removal into the 1.0 release will be more disruptive than I want it to be.

So with the 1.0.0 release, you will be able to use `ActiveRecord::KSUID[:my_field, auto_gen: false]` to do this, as well as `attribute :my_field, :ksuid`.

If the gem evolves enough to warrant a 2.0 release, I will remove `ActiveRecord::KSUID.[]` at that point.
